import type { Metadata } from "next";
import { Geist, Roboto, Lato, Poppins } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/header/header";
import { Footer } from "@/components/footer/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const roboto = Roboto({
  variable: "--font-geist-roboto",
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "Halal Market",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${roboto.variable} antialiased `}
      >
        <div className="flex flex-col justify-between min-h-screen">
          <div className="flex flex-col justify-between">
            <Header />
            {children}
          </div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
